###############################################################################
# Makefile for the project BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3
###############################################################################

## General Flags
PROJECT = BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3
MCU = atmega8
TARGET = BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.elf
CC = avr-gcc.exe

## Options common to compile, link and assembly rules
COMMON = -mmcu=$(MCU)

## Compile options common for all C compilation units.
CFLAGS = $(COMMON)
CFLAGS += -Wall -gdwarf-2 -Os -std=gnu99 -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums
CFLAGS += -MD -MP -MT $(*F).o -MF dep/$(@F).d 

## Assembly specific flags
ASMFLAGS = $(COMMON)
ASMFLAGS += $(CFLAGS)
ASMFLAGS += -x assembler-with-cpp -Wa,-gdwarf2

## Linker flags
LDFLAGS = $(COMMON)
LDFLAGS +=  -Wl,-Map=BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.map


## Intel Hex file production flags
HEX_FLASH_FLAGS = -R .eeprom

HEX_EEPROM_FLAGS = -j .eeprom
HEX_EEPROM_FLAGS += --set-section-flags=.eeprom="alloc,load"
HEX_EEPROM_FLAGS += --change-section-lma .eeprom=0 --no-change-warnings


## Objects that must be built in order to link
OBJECTS = BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.o 

## Objects explicitly added by the user
LINKONLYOBJECTS = 

## Build
all: $(TARGET) BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.hex BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.eep BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.lss size

## Compile
BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.o: ../BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.c
	$(CC) $(INCLUDES) $(CFLAGS) -c  $<

##Link
$(TARGET): $(OBJECTS)
	 $(CC) $(LDFLAGS) $(OBJECTS) $(LINKONLYOBJECTS) $(LIBDIRS) $(LIBS) -o $(TARGET)

%.hex: $(TARGET)
	avr-objcopy -O ihex $(HEX_FLASH_FLAGS)  $< $@

%.eep: $(TARGET)
	-avr-objcopy $(HEX_EEPROM_FLAGS) -O ihex $< $@ || exit 0

%.lss: $(TARGET)
	avr-objdump -h -S $< > $@

size: ${TARGET}
	@echo
	@avr-size -C --mcu=${MCU} ${TARGET}

## Clean target
.PHONY: clean
clean:
	-rm -rf $(OBJECTS) BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.elf dep/* BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.hex BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.eep BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.lss BLACK_LINE_FOLLOWER_for_ATmega8_iBOT_mini_V3.map


## Other dependencies
-include $(shell mkdir dep 2>/dev/null) $(wildcard dep/*)

